Make failing rsync's in do_rsync_backup() more robust.
A failed call to rsync might cause dangling pg_start_backup()
calls. Fix this by explicitely checking wether rsync failed and
issue a pg_stop_backup() in this case. Removing the temp file
for the base backup should be handled by the subsequent trap then.

diff --git a/pg_backup_ctl b/pg_backup_ctl
--- a/pg_backup_ctl
+++ b/pg_backup_ctl
@@ -555,7 +555,18 @@ do_rsync_basebackup() {
     fi
 
     psql -c "SELECT pg_start_backup('$fn');" >/dev/null
-    $rsync_cmd "$datadir/" "$tmpfn/"
+
+    ## Catch non-zero exit code explicitely and don't rely on set -e. We need
+    ## to issue a pg_stop_backup(), otherwise this would be hanging around
+    ## forever.
+    $rsync_cmd "$datadir/" "$tmpfn/" || status=$?
+
+    ## non-zero exit status means failed rsync
+    if [ "$status" -ne 0 ]; then
+        # NOTE: We don't want to see any NOTICE messages here, but error messages...
+        PGOPTIONS='--client-min-messages=WARNING' psql -c "SELECT pg_stop_backup();" 1>/dev/null
+        return $status
+    fi
 
     ## The basebackup for PGDATA should be completed now, we need to
     ## check if there are any remaining tablespaces to be synced. We do
