Fix signal cleanup code for do_basebackup() and do_streambackup().
With commit 8962fa9e4194905a3b91113d88cf9c833f5a945a we are
starting to support at least Solaris and OSX as non-Linux platforms
and aim to emulate the flock locking behavior via mkdir within
run_with_lock(). However, since we are using trap as cleanup
within run_with_lock(), we must take care for not overwriting these
cleanup code within all other nested actions. Candidates here are
do_basebackup() and do_streambackup(). This commit fixes their
trap handlers to not overwrite the actions installed by run_with_lock().

diff --git a/pg_backup_ctl b/pg_backup_ctl
--- a/pg_backup_ctl
+++ b/pg_backup_ctl
@@ -234,7 +234,7 @@ run_with_lock()
 
         if mkdir "$LOCK" >/dev/null 2>&1
         then
-            trap "rmdir '$LOCK'" 0 2 3 15
+            trap "rm -rf '$LOCK'" INT TRAP QUIT ABRT TERM EXIT
             chmod 0 "$LOCK" # discourage anyone from messing with it else the rmdir might fail
         else
             echo >&2 "Lock ($LOCK) exists. exiting"
@@ -457,7 +457,14 @@ do_streambackup() {
 
     local tmpfn="$archivedir/base/.streaming_backup_$ts.in-progress"
     local fn="$archivedir/base/streaming_backup_$ts"
-    trap "rm -rf $tmpfn" 0 2 3 15 # clean up on error
+
+    ##
+    ## XXX: Take care for trap here, since run_with_lock() might already have
+    ##      installed it's cleanup code to remove the lock file for non-Linux
+    ##      platforms. We must not overwrite its cleanup action, so make
+    ##      sure to keep it.
+    ##      
+    trap "rm -rf $tmpfn && rmdir '$LOCK' > /dev/null 2>&1" INT TRAP QUIT ABRT TERM EXIT # clean up on error
 
     [ -d "$fn" ] && error "Streaming basebackup $fn already exists"
     # NOTE: We don't want to see any NOTICE messages here...
@@ -478,7 +485,14 @@ do_basebackup() {
     local ts="$(timestamp)"
     local tmpfn="$archivedir/base/.basebackup_$ts.tar.gz.in-progress"
     local fn="$archivedir/base/basebackup_$ts.tar.gz"
-    trap "rm -f $tmpfn" 0 2 3 15 # clean up on error
+
+    ##
+    ## XXX: Take care for trap here, since run_with_lock() might already have
+    ##      installed it's cleanup code to remove the lock file for non-Linux
+    ##      platforms. We must not overwrite its cleanup action, so make
+    ##      sure to keep it.
+    ##      
+    trap "rm -f $tmpfn && rmdir '$LOCK' > /dev/null 2>&1" INT TRAP QUIT ABRT TERM EXIT # clean up on error
 
     [ -f "$fn" ] && error "Basebackup $fn already exists"
     psql -c "SELECT pg_start_backup('$fn');" >/dev/null
@@ -996,6 +1010,8 @@ do_ls() {
     walcount=$(ls -1 "$archivedir/log/" | $GREP -E '^[0-9A-Z]{24}\.?[gz]*$' | wc -l)
     echo $hdrline
     printf "Total size occupied by %d WAL segments in archive: %-9s\n" $walcount $wallogsize
+
+    return 0
 }
 
 # main
